"""High-level SaaS instance operations executed locally by the agent.

These commands encapsulate all local filesystem and Docker operations
required to provision/deprovision an Odoo instance, so the control plane
only needs to send a single high-level spec instead of many raw Docker calls.
"""

from __future__ import annotations

import logging
import pathlib
import re
from typing import Any

from agent.security import redact

logger = logging.getLogger(__name__)

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

# A tenant slug is only ever a lowercased identifier on the control-plane
# side (berth-platform routers/instances.py). Validating it here anyway:
# the slug is joined onto DATA_ROOT_PATH to build directories that get
# written to *and* bind-mounted into a container, so `../../etc` or an
# absolute value would escape the data root (pathlib drops the left side
# on an absolute join) — defense in depth against any control-plane bug
# that lets an unsanitized value through.
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,62}$")


def _safe_slug(slug: object) -> str:
    if not isinstance(slug, str) or not _SLUG_RE.match(slug):
        raise ValueError(f"Invalid instance slug: {slug!r}")
    return slug


class InstanceCommands:
    def __init__(self, docker_client: Any, data_root_path: str) -> None:
        self._docker = docker_client
        self._data_root = pathlib.Path(data_root_path)

    # ------------------------------------------------------------------
    # Provision
    # ------------------------------------------------------------------

    def provision(self, params: dict) -> dict:
        """Provision a full Odoo instance.

        Expected params (built by OdooDriver._provision_via_agent):
          slug, db_name, image, odoo_config_content, config_container_path,
          extra_addons_paths, docker_network, tunnel_token, platform,
          cpu_cores, ram_mb, hostname, tenant_base_domain, cert_resolver,
          init_base
        """
        slug = _safe_slug(params["slug"])
        image = params["image"]
        platform = params.get("platform") or None
        network = params.get("docker_network", "berth_platform_proxy")
        domain = params.get("tenant_base_domain", "localhost")

        slug_dir = self._data_root / slug

        # 1. Create required directories
        for sub in ("filestore", "sessions", "addons", "conf"):
            (slug_dir / sub).mkdir(parents=True, exist_ok=True)
        logger.info("Directories created for %s", slug)

        # 2. Ensure Docker network exists
        self._ensure_network(network)

        # 3. Pull image
        try:
            self._docker.images.get(image)
        except Exception:
            logger.info("Pulling image %s (platform=%s)", image, platform)
            pull_kwargs: dict = {"repository": image}
            if platform:
                pull_kwargs["platform"] = platform
            auth_config = params.get("auth_config")
            if auth_config is not None:
                pull_kwargs["auth_config"] = auth_config
            self._docker.api.pull(**pull_kwargs)

        # 3b. Normalize ownership of the tenant data dirs.
        # The agent runs as uid 1000 and cannot fix files left root-owned by a
        # previous container (a prior run, a reused slug). The Odoo container
        # runs as uid 1000 too, so root-owned leftovers under filestore/ make
        # every _file_write fail with PermissionError (the DB then references
        # filestore files that were never written — "corrupted" instance), and
        # root-owned .git dirs under addons/ make gitaggregate reject the
        # worktrees as "dubious ownership". Best-effort: a throwaway root
        # container chowns them back. Single-tenant platform-owned box.
        self._normalize_data_dir_perms(slug_dir, image)

        # Discover addon repositories baked into the image. The control plane
        # can discover these for a local Docker daemon, but the agent runs on
        # a different host and therefore must inspect the image here. Keep
        # synced tenant addons first so a checked-out repo wins over the
        # fallback version baked into the image.
        extra_paths = self._merge_addon_paths(
            image, params.get("extra_addons_paths") or []
        )
        addons_path = (
            ",".join(extra_paths) if extra_paths else "/mnt/extra-addons"
        )

        # 4. Write odoo.conf with the complete addon path list. The config
        # generated by the control plane may contain only /mnt/extra-addons;
        # replace that value after discovering image-baked OCA repositories.
        config_content = params.get("odoo_config_content", "")
        config_content = self._replace_addons_path(config_content, addons_path)
        conf_path = slug_dir / "conf" / "odoo.conf"
        conf_path.write_text(config_content, encoding="utf-8")
        logger.info(
            "Config written: %s (addons_path=%s)", conf_path, addons_path
        )

        # 5. Build volumes (relative paths resolved by ContainerCommands._resolve_volumes,
        #    but here we build absolute paths directly since we know data_root_path)
        host_base = str(self._data_root / slug)
        config_container_path = params.get(
            "config_container_path", "/etc/odoo/odoo.conf"
        )
        volumes: dict[str, dict[str, str]] = {
            f"{host_base}/filestore": {
                "bind": "/var/lib/odoo/filestore",
                "mode": "rw",
            },
            f"{host_base}/sessions": {
                "bind": "/var/lib/odoo/sessions",
                "mode": "rw",
            },
            f"{host_base}/addons": {"bind": "/mnt/extra-addons", "mode": "rw"},
            f"{host_base}/conf/odoo.conf": {
                "bind": config_container_path,
                "mode": "ro",
            },
        }

        # 6. Build labels (Traefik routing)
        container_name = f"saas_{slug}"
        labels = self._build_traefik_labels(
            slug,
            container_name,
            network,
            domain,
            hostname=params.get("hostname"),
            cert_resolver=params.get("cert_resolver") or "letsencrypt",
        )

        # 7. Build environment
        env = {
            "ADDONS_PATH": addons_path,
        }
        # DB connection env (HOST/PORT/USER/PASSWORD) — the ooops OCB
        # entrypoint reads these to wait for and authenticate against the
        # external Postgres. Strings only; skip anything non-str/None.
        db_env = params.get("db_env")
        if isinstance(db_env, dict):
            for k, v in db_env.items():
                if isinstance(k, str) and isinstance(v, str):
                    env[k] = v

        # 8. Resource limits
        cpu_cores = params.get("cpu_cores")
        ram_mb = params.get("ram_mb")
        nano_cpus = int(cpu_cores * 1e9) if cpu_cores else None
        mem_limit = f"{ram_mb}m" if ram_mb else None

        # 9. Build the odoo command (same pattern as control plane
        #    docker_manager.spawn_instance). -d/--db-filter mirror what's
        #    already enforced in odoo.conf (db_name/dbfilter, written above);
        #    -i base has no config-file equivalent — it's CLI-only. Whether
        #    to pass it is decided once on the control plane
        #    (OdooDriver._provision_via_agent / _replace_container_via_agent,
        #    via backup_manager.is_base_module_installed) and trusted
        #    verbatim here — the agent never re-derives it locally. Passing
        #    -i base on every boot (not just a genuinely fresh database)
        #    unconditionally reapplies base's noupdate="1" data, silently
        #    resetting the admin password to Odoo's factory default "admin"
        #    on every restart. A missing/omitted init_base defaults to
        #    False (never re-init) rather than True, so an older control
        #    plane talking to a newer agent fails safe.
        db_name = params["db_name"]
        odoo_cmd = ["odoo", "-d", db_name]
        if params.get("init_base"):
            odoo_cmd += ["-i", "base"]
        odoo_cmd += ["--db-filter", f"^{db_name}$"]
        _wait = 'until pg_isready -h "$HOST" -p "$PORT" -U "$USER" 2>/dev/null; do sleep 2; done'
        import shlex

        # The command is wrapped in `sh -c`, so the image entrypoint cannot
        # inject its usual --config argument (it only does that when the
        # first argv item is `odoo`). Pass the mounted config explicitly or
        # Odoo silently falls back to default@default and ignores the remote
        # PostgreSQL settings.
        odoo_cmd.insert(1, "--config=/etc/odoo/odoo.conf")
        command = [
            "sh",
            "-c",
            f"{_wait} && {' '.join(shlex.quote(a) for a in odoo_cmd)}",
        ]

        run_kwargs: dict[str, Any] = {
            "image": image,
            "name": container_name,
            "detach": True,
            "environment": env,
            "labels": labels,
            "volumes": volumes,
            "network": network,
            "command": command,
            "restart_policy": {"Name": "unless-stopped"},
            "hostname": params.get("hostname") or slug,
        }
        if platform:
            run_kwargs["platform"] = platform
        if nano_cpus:
            run_kwargs["nano_cpus"] = nano_cpus
        if mem_limit:
            run_kwargs["mem_limit"] = mem_limit

        # Idempotent re-provision: a stale container with this name (a prior
        # attempt that got far enough to create it, then failed/timed out)
        # would otherwise 409 forever.
        for stale in (container_name, f"{container_name}_cloudflared"):
            try:
                self._docker.containers.get(stale).remove(force=True)
                logger.info(
                    "Removed stale container %s before re-provision", stale
                )
            except Exception:  # noqa: BLE001 — NotFound or already gone
                pass

        container = self._docker.containers.run(**run_kwargs)
        logger.info(
            "Instance container started: %s (%s)",
            container.name,
            container.short_id,
        )

        # Cloudflare tunnel sidecar (if token provided) — provisioned separately
        cloudflared_id: str | None = None
        tunnel_token = params.get("tunnel_token")
        if tunnel_token:
            cloudflared_id = self._spawn_cloudflared(
                slug, tunnel_token, network
            )

        return {
            "container_id": container.id,
            "cloudflared_container_id": cloudflared_id,
        }

    # ------------------------------------------------------------------
    # Deprovision
    # ------------------------------------------------------------------

    def deprovision(self, params: dict) -> dict:
        for name_or_id in filter(
            None,
            [
                params.get("cloudflared_container_id"),
                params.get("container_id"),
            ],
        ):
            try:
                self._docker.containers.get(name_or_id).remove(force=True)
                logger.info("Removed container %s", name_or_id)
            except Exception as exc:
                logger.warning(
                    "Could not remove container %s: %s", name_or_id, exc
                )
        return {}

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _normalize_data_dir_perms(
        self, slug_dir: pathlib.Path, image: str
    ) -> None:
        """chown filestore/sessions/addons to uid 1000 via a root container.

        Mirrors what docker_manager.spawn_instance does on the local path
        (chown/chmod to the runtime uid). The agent runs as uid 1000 and
        cannot fix root-owned leftovers from a prior run itself, so it uses
        a throwaway root container. Best-effort — never fail provisioning.
        Runs at provision/replace time, not on every boot.

        ponytail: chown -R rescans the whole filestore on every replace
        (repo sync); fine today (replace isn't hot, tree is usually
        already-correct so it's mostly stat traffic). If a large filestore
        makes it drag, gate on params["init_base"] or add `chown --from=0`.
        """
        targets = [
            f"/data/{sub}"
            for sub in ("filestore", "sessions", "addons")
            if (slug_dir / sub).exists()
        ]
        if not targets:
            return
        try:
            self._docker.containers.run(
                image,
                entrypoint=["chown", "-R", "1000:1000", *targets],
                command=[],  # drop the image's default CMD (odoo -i base)
                user="0:0",
                volumes={str(slug_dir): {"bind": "/data", "mode": "rw"}},
                remove=True,
                detach=False,
                network_mode="none",
            )
            logger.info("Normalized data dir ownership for %s", slug_dir.name)
        except Exception:
            logger.warning(
                "Could not normalize data dir ownership for %s "
                "(instance may fail filestore writes)",
                slug_dir.name,
                exc_info=True,
            )

    def _discover_image_addon_paths(self, image: str) -> list[str]:
        """Discover repository roots containing addons baked into *image*."""
        probe = None
        try:
            probe = self._docker.containers.create(
                image,
                entrypoint=[
                    "find",
                    "/opt/odoo/extra-addons",
                    "-mindepth",
                    "2",
                    "-maxdepth",
                    "2",
                    "-type",
                    "d",
                ],
            )
            probe.start()
            result = probe.wait(timeout=60)
            if result.get("StatusCode") != 0:
                return []
            return sorted(
                line.decode().strip()
                for line in probe.logs(stdout=True, stderr=False).splitlines()
                if line.strip()
            )
        except Exception:
            logger.warning(
                "Could not discover baked addon paths in image %s",
                image,
                exc_info=True,
            )
            return []
        finally:
            if probe is not None:
                try:
                    probe.remove(force=True)
                except Exception:
                    logger.debug(
                        "Could not remove addon discovery container",
                        exc_info=True,
                    )

    def _merge_addon_paths(
        self, image: str, extra_paths: list[str]
    ) -> list[str]:
        """Merge tenant addons with image addons, preferring tenant paths."""
        custom = [
            path for path in extra_paths if isinstance(path, str) and path
        ]
        fingerprints = {
            "/".join(path.rstrip("/").split("/")[-2:])
            for path in custom
            if len(path.rstrip("/").split("/")) >= 2
        }
        baked = [
            path
            for path in self._discover_image_addon_paths(image)
            if "/".join(path.rstrip("/").split("/")[-2:]) not in fingerprints
        ]
        merged = custom + [path for path in baked if path not in custom]
        logger.info(
            "Addon paths for %s: %d tenant + %d baked",
            image,
            len(custom),
            len(merged) - len(custom),
        )
        return merged

    @staticmethod
    def _replace_addons_path(config: str, addons_path: str) -> str:
        """Replace or add the addons_path option in an Odoo config."""
        replacement = f"addons_path = {addons_path}"
        updated, count = re.subn(
            r"(?m)^\s*addons_path\s*=.*$", replacement, config
        )
        if count:
            return updated
        if "[options]" in updated:
            return updated.replace("[options]", f"[options]\n{replacement}", 1)
        return f"[options]\n{replacement}\n{updated}"

    def _ensure_network(self, network: str) -> None:
        try:
            self._docker.networks.get(network)
        except Exception:
            self._docker.networks.create(network, driver="bridge")
            logger.info("Created Docker network: %s", network)

    def _build_traefik_labels(
        self,
        slug: str,
        container_name: str,
        network: str,
        domain: str,
        hostname: str | None = None,
        cert_resolver: str = "letsencrypt",
    ) -> dict:
        host = hostname or f"{slug}.{domain}"
        router = f"saas-{slug}"
        return {
            "traefik.enable": "true",
            f"traefik.http.routers.{router}.rule": f"Host(`{host}`)",
            f"traefik.http.routers.{router}.entrypoints": "websecure",
            f"traefik.http.routers.{router}.tls": "true",
            f"traefik.http.routers.{router}.tls.certresolver": cert_resolver,
            f"traefik.http.services.{router}.loadbalancer.server.port": "8069",
            "saas.instance": slug,
            "saas.managed": "true",
        }

    def _spawn_cloudflared(
        self, slug: str, tunnel_token: str, network: str
    ) -> str | None:
        try:
            cf_name = f"saas_{slug}_cloudflared"
            cf = self._docker.containers.run(
                "cloudflare/cloudflared:latest",
                name=cf_name,
                detach=True,
                network=network,
                command=[
                    "tunnel",
                    "--no-autoupdate",
                    "run",
                    "--token",
                    tunnel_token,
                ],
                restart_policy={"Name": "unless-stopped"},
                labels={"saas.instance": slug, "saas.role": "cloudflared"},
            )
            logger.info("Cloudflared sidecar started: %s", cf.short_id)
            return cf.id
        except Exception as exc:
            logger.warning(
                "Could not spawn cloudflared for %s: %s",
                slug,
                redact(str(exc)),
            )
            return None
